- name: Ensure firewalld is configured with Rich Rules
      ansible.posix.firewalld:
        rich_rule: 'rule family="ipv4" source address="{{ item.0 }}" port port="{{ item.1 }}" protocol="tcp" accept'
        permanent: yes
        state: enabled
        immediate: yes
      with_nested:
        - "{{ ip_nguon }}"
        - "{{ ports }}"
      when: ansible_os_family == "RedHat"
