---
- name: Open Firewall Rules for Multiple Sources and Ports
  hosts: all
  gather_facts: no
  collections:
    - community.windows

  tasks:
    - name: Create Firewall Rules
      community.windows.win_firewall_rule:
        name: "Allow_Traffic_From_{{ item.0 | trim }}_to_{{ item.1 | trim }}"
        localport: "{{ item.1 | trim }}"
        remoteip: "{{ item.0 | trim }}"
        action: allow
        direction: inbound
        protocol: tcp
        state: present
        enabled: yes
      # Sử dụng split('\n') để biến chuỗi từ Survey thành List
      with_nested:
        - "{{ ip_nguon.split('\n') }}"
        - "{{ ports.split('\n') }}"
      # Bỏ qua các dòng trống nếu người dùng lỡ tay enter dư
      when: item.0 | trim != "" and item.1 | trim != ""
